[mypy]
python_version = 3.12
warn_unused_configs = True
ignore_missing_imports = True

# Third-party stub packages with known issues we don't control:
[mypy-rdkit.*]
ignore_errors = True
follow_imports = skip

[mypy-sklearn.*]
ignore_errors = True
follow_imports = skip
